// Generated by scripts/generate-apple-tokens.mjs from design/tokens.json.
// Do not edit by hand — edit the JSON and re-run `npm run tokens:apple`.
//
// design/tokens.json is the parity source shared with the web build
// (src/styles/tokens.css is generated from the same file). If a colour here
// disagrees with the web, the JSON is wrong, not this file.

import CoreGraphics

public enum Tokens {

    /// A colour token, carried as both its source hex and its integer channels
    /// so a platform `Color` can be built without parsing strings.
    public struct TokenColor: Sendable, Equatable {
        public let hex: UInt32
        public let r: Int
        public let g: Int
        public let b: Int

        public init(hex: UInt32, r: Int, g: Int, b: Int) {
            self.hex = hex
            self.r = r
            self.g = g
            self.b = b
        }
    }

    public struct MotionToken: Sendable, Equatable {
        public enum Easing: Sendable { case ease, easeInOut }
        public let duration: Double
        public let easing: Easing

        public init(duration: Double, easing: Easing) {
            self.duration = duration
            self.easing = easing
        }
    }

    public enum Color {
        public enum Dark {
        /// `#16130f`
        public static let bg = TokenColor(hex: 0x16130F, r: 22, g: 19, b: 15)
        /// `#201b16`
        public static let bgPanel = TokenColor(hex: 0x201B16, r: 32, g: 27, b: 22)
        /// `#3a322a`
        public static let border = TokenColor(hex: 0x3A322A, r: 58, g: 50, b: 42)
        /// `#f1ece3`
        public static let text = TokenColor(hex: 0xF1ECE3, r: 241, g: 236, b: 227)
        /// `#b8ada0`
        public static let textDim = TokenColor(hex: 0xB8ADA0, r: 184, g: 173, b: 160)
        /// `#e8823a`
        public static let accent = TokenColor(hex: 0xE8823A, r: 232, g: 130, b: 58)
        /// `#7fae8a`
        public static let allClear = TokenColor(hex: 0x7FAE8A, r: 127, g: 174, b: 138)
        /// `#c9b46a`
        public static let something = TokenColor(hex: 0xC9B46A, r: 201, g: 180, b: 106)
        /// `#d68a4a`
        public static let smells = TokenColor(hex: 0xD68A4A, r: 214, g: 138, b: 74)
        /// `#b85c3a`
        public static let tastes = TokenColor(hex: 0xB85C3A, r: 184, g: 92, b: 58)
        /// `#7a4030`
        public static let smokeshow = TokenColor(hex: 0x7A4030, r: 122, g: 64, b: 48)
        }

        public enum Light {
        /// `#faf7f2`
        public static let bg = TokenColor(hex: 0xFAF7F2, r: 250, g: 247, b: 242)
        /// `#ffffff`
        public static let bgPanel = TokenColor(hex: 0xFFFFFF, r: 255, g: 255, b: 255)
        /// `#e2d9cc`
        public static let border = TokenColor(hex: 0xE2D9CC, r: 226, g: 217, b: 204)
        /// `#241f19`
        public static let text = TokenColor(hex: 0x241F19, r: 36, g: 31, b: 25)
        /// `#6b6156`
        public static let textDim = TokenColor(hex: 0x6B6156, r: 107, g: 97, b: 86)
        /// `#e8823a`
        public static let accent = TokenColor(hex: 0xE8823A, r: 232, g: 130, b: 58)
        /// `#7fae8a`
        public static let allClear = TokenColor(hex: 0x7FAE8A, r: 127, g: 174, b: 138)
        /// `#c9b46a`
        public static let something = TokenColor(hex: 0xC9B46A, r: 201, g: 180, b: 106)
        /// `#d68a4a`
        public static let smells = TokenColor(hex: 0xD68A4A, r: 214, g: 138, b: 74)
        /// `#b85c3a`
        public static let tastes = TokenColor(hex: 0xB85C3A, r: 184, g: 92, b: 58)
        /// `#7a4030`
        public static let smokeshow = TokenColor(hex: 0x7A4030, r: 122, g: 64, b: 48)
        }
    }

    /// Base point sizes, converted from the web's rem scale at a 16pt root.
    /// Render them through `Typography` so Dynamic Type still applies.
    public enum TypeScale {
        public static let xs: CGFloat = 11.2
        public static let sm: CGFloat = 12.8
        public static let base: CGFloat = 15.2
        public static let md: CGFloat = 17.6
        public static let lg: CGFloat = 20.8
        public static let xl: CGFloat = 25.6
        public static let display: CGFloat = 41.6
    }

    public enum Radius {
        public static let sm: CGFloat = 8
        public static let md: CGFloat = 12
        public static let lg: CGFloat = 16
        /// `999px` on the web — a capsule here.
        public static let pill: CGFloat = 999
    }

    public enum Motion {
        /// `0.35s ease`
        public static let base = MotionToken(duration: 0.35, easing: .ease)
        /// `0.4s ease`
        public static let slow = MotionToken(duration: 0.4, easing: .ease)
        /// `1.2s ease-in-out`
        public static let bounce = MotionToken(duration: 1.2, easing: .easeInOut)
    }
}
