// Review fixtures for the /asdfasdf candidate.
//
// These are the SAME payloads the iOS build renders (contract §10, generated by
// scripts/generate-apple-fixtures.mjs from src/lib/forecast.js), so a design
// review here is looking at the same numbers Kelly's app is looking at. Nothing
// in this directory ships to the real app.
//
// The fixtures are pinned to early August 2026, which would put the sun in the
// wrong part of the sky and date every label. `rebase()` slides the whole
// series so the fixture's `now` lands on the current hour — after which the
// verdict, the day summaries and the headline are all recomputed by the real
// modules rather than read off the fixture. That is the point: the prototype
// exercises production logic, and only the PM2.5 series is canned.

import clearStayingClear from '../../apple/Sources/SmokeshowKit/Resources/Fixtures/clear-staying-clear.json';
import cleanSmokeArriving from '../../apple/Sources/SmokeshowKit/Resources/Fixtures/clean-smoke-arriving.json';
import smokeNowClearing from '../../apple/Sources/SmokeshowKit/Resources/Fixtures/smoke-now-clearing.json';
import smokeNeverClears from '../../apple/Sources/SmokeshowKit/Resources/Fixtures/smoke-never-clears.json';
import modelGaps from '../../apple/Sources/SmokeshowKit/Resources/Fixtures/model-gaps.json';

// Every fixture is Minneapolis; the payload carries coordinates but no place
// name, and inventing one per scenario would be the kind of fake detail this
// page is supposed to avoid.
const PLACE = 'Minneapolis, MN';

export const SCENARIOS = [
  { id: 'smoke-now-clearing', label: 'Smoke, clearing', fixture: smokeNowClearing },
  { id: 'clean-smoke-arriving', label: 'Clear, smoke coming', fixture: cleanSmokeArriving },
  { id: 'smoke-never-clears', label: 'Never clears', fixture: smokeNeverClears },
  { id: 'clear-staying-clear', label: 'All clear', fixture: clearStayingClear },
  { id: 'model-gaps', label: 'Model gaps', fixture: modelGaps },
  // Every real fixture is single-model, so none of them carry a `diverge`
  // hour and the treatment for the case that matters most would be
  // unreviewable. This one forces a split across a run of afternoon hours.
  // Synthesised, and the review panel says so.
  {
    id: 'models-split',
    label: 'Models split',
    fixture: smokeNowClearing,
    forceDivergeFromNow: [6, 20],
  },
];

// `timesUTC` entries are stored WITHOUT the trailing Z, because that is what
// Open-Meteo returns and what every src/lib module expects (they all do
// `new Date(timesUTC[i] + 'Z')`). Slicing to 19 chars drops the Z and the
// milliseconds in one step.
function toSeriesStamp(ms) {
  return new Date(ms).toISOString().slice(0, 19);
}

export function rebase(fixture, { forceDivergeFromNow = null } = {}) {
  const hours = fixture.hours ?? [];
  const nowIndex = fixture.now.index;

  // Snap the wall clock to the top of the hour: the series is hourly, and a
  // half-hour offset would put "now" between two samples.
  const realNow = new Date();
  realNow.setUTCMinutes(0, 0, 0);
  const delta = realNow.getTime() - Date.parse(hours[nowIndex].t);

  // Per-hour model agreement, straight off the payload: 'agree' | 'fade' |
  // 'diverge' (contract §4, computed by lib/agreement.js server-side).
  const agreement = hours.map((h) => h.agreement ?? 'agree');
  let summary = fixture.agreement ?? null;
  if (forceDivergeFromNow) {
    const [from, to] = forceDivergeFromNow;
    for (let i = nowIndex + from; i <= nowIndex + to && i < agreement.length; i++) {
      agreement[i] = 'diverge';
    }
    summary = { multiModel: true, diverged: true, label: 'Models split on timing' };
  }

  return {
    timesUTC: hours.map((h) => toSeriesStamp(Date.parse(h.t) + delta)),
    // A null hour stays null. The contract's rule is that the model returns
    // null for hours it has nothing to say about, and zero would be a claim
    // about clean air — the curve draws these as gaps, never at the baseline.
    pm25: hours.map((h) => h.pm25),
    nowIndex,
    timezone: fixture.location.timezone,
    lat: fixture.location.requested.lat,
    lon: fixture.location.requested.lon,
    place: PLACE,
    scale: fixture.scale ?? [],
    measured: fixture.measured ?? null,
    // The three days before today, already collapsed to a level and a range by
    // the payload builder. What the "‹" button reveals.
    pastDays: fixture.pastDays ?? [],
    agreement,
    agreementSummary: summary,
  };
}
